name: Build

on:
  workflow_dispatch:

jobs:
  build-meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Generate build metadata
        run: |
          VERSION=$(node -p "require('./package.json').version")
          BRANCH=${GITHUB_REF_NAME}
          COMMIT=${GITHUB_SHA}
          echo "{\"branch\":\"${BRANCH}\",\"version\":\"${VERSION}\",\"commit\":\"${COMMIT}\"}" > build-meta.json
          cat build-meta.json
      - uses: actions/upload-artifact@v6
        with:
          name: build-meta
          path: build-meta.json
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Read version
        run: |
          $version = node -p "require('./package.json').version"
          echo "VERSION=$version" >> $env:GITHUB_ENV
      - run: pnpm run package
      - uses: dyr1980/inno-setup-action-cli@main
        with:
          filepath: ./release/build-windows.iss
          variables: /DMyAppVersion=${{ env.VERSION }} /DMyAppId=${{ secrets.MYAPPID }}
      - name: Rename setup file
        run: |
          Rename-Item -Path "./out/MusicFreeDesktop-${{ env.VERSION }}-Setup.exe" -NewName "MusicFree-${{ env.VERSION }}-win32-x64-setup.exe"
      - name: Generate portable
        run: |
          New-Item -ItemType Directory -Path "./out/MusicFree-win32-x64/portable" -Force
          New-Item -ItemType File -Path "./out/MusicFree-win32-x64/portable/.portable" -Force
      - name: Archive portable
        run: |
          Compress-Archive -Path "./out/MusicFree-win32-x64/*" -DestinationPath "./out/MusicFree-${{ env.VERSION }}-win32-x64-portable.zip"
      - uses: actions/upload-artifact@v6
        with:
          name: MusicFree-${{ env.VERSION }}-win32-x64-setup
          path: ./out/MusicFree-${{ env.VERSION }}-win32-x64-setup.exe
          retention-days: 30
      - uses: actions/upload-artifact@v6
        with:
          name: MusicFree-${{ env.VERSION }}-win32-x64-portable
          path: ./out/MusicFree-${{ env.VERSION }}-win32-x64-portable.zip
          retention-days: 30
